### ISSUE TITLE
Fix Freq data import

### ISSUE THREAD

**Issue by chrisdunelm** [chrisdunelm/UkEnergyWatch#26]

**Comment by chrisdunelm** [comment]
Exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetByteArrayAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Ukew.Utils.Tasks.ForwardingAwaiter`1.GetResult() in /home/chris/Projects/UkEnergyWatch/ukewlib/Utils/Tasks/ForwardingAwaiter.cs:line 33
   at Ukew.Elexon.ElexonDownloader.<GetXmlAsync>d__3.MoveNext() in /home/chris/Projects/UkEnergyWatch/ukewlib/Elexon/ElexonDownloader.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Ukew.Utils.Tasks.ForwardingAwaiter`1.GetResult() in /home/chris/Projects/UkEnergyWatch/ukewlib/Utils/Tasks/ForwardingAwaiter.cs:line 33
   at Ukew.Elexon.Freq.<GetAsync>d__8.MoveNext() in /home/chris/Projects/UkEnergyWatch/ukewlib/Elexon/Freq.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Ukew.Utils.Tasks.ForwardingAwaiter`1.GetResult() in /home/chris/Projects/UkEnergyWatch/ukewlib/Utils/Tasks/ForwardingAwaiter.cs:line 33
   at Ukew.Applications.FetchFreq.<Start0>d__8.MoveNext() in /home/chris/Projects/UkEnergyWatch/ukewlib/Applications/FetchFreq.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ukew.Applications.FetchFreq.<Start>d__7.MoveNext() in /home/chris/Projects/UkEnergyWatch/ukewlib/Applications/FetchFreq.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ukew.Program.<GetFreq>d__2.MoveNext() in /home/chris/Projects/UkEnergyWatch/ukew_getdata/Program.cs:line 60
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Ukew.Program.<>c.<Main>b__0_2(GetFreqOptions opts) in /home/chris/Projects/UkEnergyWatch/ukew_getdata/Program.cs:line 29
   at Ukew.Program.Main(String[] args) in /home/chris/Projects/UkEnergyWatch/ukew_getdata/Program.cs:line 20
```

**Comment by chrisdunelm** [comment]
Fixed in https://github.com/chrisdunelm/UkEnergyWatch/commit/5978ffd71a58ee6c766af914cb6fa12f8b7ee116
